### ISSUE TITLE
Magic Occupancy doesn't work any longer

### ISSUE THREAD

**Issue by HolgerAusB** [Jason-Morcos/homebridge-magic-occupancy#54]
I believe that starts with one of the HomeKit Updates in tvOS a few months ago.

My Assets from Magic Occupancy are not answering any longer. I had two not too complicated assets, which worked fine in child bridges for months but now they are stopping to work.

I removed assets, restart HB and added one again. The dummy LightSwitch should triggering an automation to start/stop ambient sound on HomePod

```json
{
    "name": "Einschlafen",
    "stayOccupiedDelay": 5400,
    "maxOccupationTimeout": 30000,
    "occupancyLogging": true,
    "persistBetweenReboots": true,
    "startOnReboot": false,
    "lightSwitchesNames": "Einschlafen ein",
    "triggerSwitchesNames": "Einschlafen 90m",
    "createMasterShutoff": false,
    "accessory": "MagicOccupancy",
    "_bridge": {
        "username": "0E:XX:XX:XX:XX:XX",
        "port": 12345,
        "name": "Einschlafen 12345",
        "debugModeEnabled": true,
        "manufacturer": "Magic Occupancy"
    }
}
```

When trying to connect the child bridge, HomeKit says, that the asset is not compatible, none of the 3 (sub)assets are shown in 'Home' and I also don't find the sub-bridge. When trying to connect again, 'Home' says that this asset needs to be reset because it is already connected to someones 'Home'.

I also tried to setting-up that asset without child-bridges, but the new assets also don't show up in 'Home'

```yml
Homebridge:      v2.0.0-beta.27
Homebridge UI:   v5.0.0-beta.49
Node.js :        v22.14.0
Magic Occupancy: v4.0.1

Hardware:        Raspberry Pi 5, 8GB
OS:              Raspian/Debian 64bit, Trixie=testing

AppleTV 4K:      A1842 (64 GB)
tvOS:            18.3
```
